# # 🚀 PART 5 — MINI PROJECT
# # 🏢 Sales Performance & Customer Segmentation Dashboard, After finishing the practice, use the same dataset and perform:
# # Step 1 — Business Dashboard Calculate: Total Sales Total Profit Overall Profit Margin Average Order Value Number of Customers Number of Orders
# # Step 2 — Customer Dashboard Create a customer summary containing Total Sales Total Profit, Order Count Average Order Value Profit Margin
# # Step 3 — Category Dashboard For each category calculate: Total Sales Total Profit Average Order Value Profit Margin Number of Orders
# # Step 4 — Customer Segmentation Create the three customer segments: High Value / Medium Value / Low Value Then calculate: Number of customers in each segment Total sales generated by each segment Total profit generated by each segment
# # Step 5 — Rankings Find: Top 5 customers by sales Top 5 customers by profit Top category by sales Top category by profit Most profitable order
# # Step 6 — Business Insights 🧠 Write at least 5 actual insights based on your output. Think about: Which customers are most valuable? Which category drives the most revenue? Is the highest-sales category also the most profitable? Which customer segment contributes most to the business? Are there customers with high sales but relatively low profit margins?
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Order_ID": range(1001, 1016),

    "Customer": [
        "Amit", "Riya", "Rahul", "Amit", "Priya",
        "Riya", "Karan", "Priya", "Rahul", "Amit",
        "Neha", "Karan", "Priya", "Riya", "Neha"
    ],

    "Category": [
        "Electronics", "Furniture", "Electronics",
        "Clothing", "Furniture", "Electronics",
        "Clothing", "Electronics", "Furniture",
        "Electronics", "Clothing", "Furniture",
        "Electronics", "Clothing", "Furniture"
    ],

    "Sales": [
        120000, 75000, 90000,
        30000, 85000, 110000,
        45000, 130000, 65000,
        95000, 40000, 70000,
        150000, 35000, 80000
    ],

    "Profit": [
        30000, 12000, 18000,
        5000, 14000, 25000,
        8000, 32000, 10000,
        22000, 6000, 11000,
        40000, 4000, 15000
    ]
})
business_dashboard = {
    "Total Sales": df["Sales"].sum(),
    "Total Profit": df["Profit"].sum(),
    "Overall Profit Margin (%)": (
        df["Profit"].sum() / df["Sales"].sum()
    ) * 100,
    "Average Order Value": df["Sales"].mean(),
    "Number of Customers": df["Customer"].nunique(),
    "Number of Orders": df["Order_ID"].count()
}

customer_dashboard = (
    df.groupby("Customer")
      .agg(
          Total_Sales=("Sales", "sum"),
          Total_Profit=("Profit", "sum"),
          Order_Count=("Order_ID", "count"),
          Average_Order_Value=("Sales", "mean")
      )
)

customer_dashboard["Profit_Margin"] = (
    customer_dashboard["Total_Profit"]
    / customer_dashboard["Total_Sales"]
) * 100

category_dashboard = (
    df.groupby("Category")
      .agg(
          Total_Sales=("Sales", "sum"),
          Total_Profit=("Profit", "sum"),
          Average_Order_Value=("Sales", "mean"),
          Number_of_Orders=("Order_ID", "count")
      )
)

category_dashboard["Profit_Margin"] = (
    category_dashboard["Total_Profit"]
    / category_dashboard["Total_Sales"]
) * 100


df["Customer_Total_Sales"] = (
    df.groupby("Customer")["Sales"]
      .transform("sum")
)

df["Customer_Total_Profit"] = (
    df.groupby("Customer")["Profit"]
      .transform("sum")
)

conditions = [
    df["Customer_Total_Sales"] >= 250000,
    df["Customer_Total_Sales"] >= 150000
]

choices = [
    "High Value",
    "Medium Value"
]

df["Customer_Segment"] = np.select(
    conditions,
    choices,
    default="Low Value"
)

customer_segments = (
    df[[
        "Customer",
        "Customer_Total_Sales",
        "Customer_Total_Profit",
        "Customer_Segment"
    ]]
    .drop_duplicates()
)

segment_dashboard = (
    customer_segments
    .groupby("Customer_Segment")
    .agg(
        Number_of_Customers=("Customer", "count"),
        Total_Sales=("Customer_Total_Sales", "sum"),
        Total_Profit=("Customer_Total_Profit", "sum")
    )
)

top_5_customers_sales = (
    customer_dashboard
    .sort_values("Total_Sales", ascending=False)
    .head(5)
)

top_5_customers_profit = (
    customer_dashboard
    .sort_values("Total_Profit", ascending=False)
    .head(5)
)

top_category_sales = (
    category_dashboard["Total_Sales"].idxmax()
)

top_category_profit = (
    category_dashboard["Total_Profit"].idxmax()
)

most_profitable_order = (
    df.loc[df["Profit"].idxmax()]
)
